dist: xenial
os: linux
language: python

python:
  - 3.6
  - 3.7
  - 3.8

cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/downloads

install: skip
script: ./ci/test.sh ${TRAVIS_PYTHON_VERSION}

jobs:
  include:

  - stage: pypi
    services:
      - docker
    env: &pypi-env
      - CIBW_BUILD="cp36-* cp37-* cp38-*"
      - CIBW_BEFORE_BUILD="pip install cython"
    install: &pypi-install
      - pip install cibuildwheel cython twine
    script: &pypi-script
      - cibuildwheel --output-dir dist
      - if [ "$TRAVIS_OS_NAME" = "linux" ]; then python setup.py sdist ; fi
      - ls dist
      - twine upload dist/* -u ${PYPI_USER} -p ${PYPI_PASSWORD}
    if: tag IS present

  - stage: pypi
    os: osx
    language: generic
    env: *pypi-env
    install: *pypi-install
    script: *pypi-script
    if: tag IS present

  - stage: pypi
    os: windows
    language: shell
    env:
      - CIBW_BUILD="cp36-* cp37-* cp38-*"
      - CIBW_BEFORE_BUILD="pip install cython"
      - PATH=/c/Python36:/c/Python36/Scripts:$PATH
    before_install:
      - choco install python3 --version 3.6.8 --no-progress -y
    install: *pypi-install
    script: *pypi-script
    if: tag IS present

  - stage: dev-docs
    install:
      - sudo apt-get install graphviz pandoc
      - python setup.py install
      - pip install -e ".[docs]"
    script: make doc
    after_success:
      - git config --global user.email "maxhalford25@gmail.com"
      - git config --global user.name "MaxHalford"
      - mike deploy dev --push --force --remote https://${GH_TOKEN}@github.com/online-ml/river.git
    if: branch = "master"

  - stage: release-docs
    install:
      - sudo apt-get install graphviz pandoc
      - python setup.py install
      - pip install -e ".[docs]"
      - make execute-notebooks
    script: make doc
    after_success:
      - git config --global user.email "maxhalford25@gmail.com"
      - git config --global user.name "MaxHalford"
      - RIVER_VERSION=$(python -c "import river; print(river.__version__)")
      - mike deploy ${RIVER_VERSION} latest --push --force --remote https://${GH_TOKEN}@github.com/river-ml/river.git
      - mike set-default latest --push --force --remote https://${GH_TOKEN}@github.com/river-ml/river.git
    if: tag IS present

env:
  global:
    secure: diU7M/lZeRtnN1cpb9nSBwtyflzmKTsB5rp3T0lgwNI24egwSITSidvMON+D1DNTHaxE/JCHpWMFvU+ivBIrBcmYZeO7tqijj3FrKPQxMZ1GiI0l7c5ifIdO0FmxjdzkzfLdlJs2wm/PuhEf9ckkMR265BpLBsfmL3/JnFu5mEKVzs5ai15Ky7ushnkhX28Bv89It+UOfD7R3zQk50a7c+8B+BkHe72mf9kJsvD9Qi8keiogGezw+eYbxcjbh13vq4YQzbaBm8eux93Zt3pfTwQZff7iX89RbwtrM7p1jFTv34tMJyyp8EJIicwhTy1PQvoPMUvSzrCajJIGCboy/FLZgbscj6monbohTlSEtpTaq9sJsfn1GB4ofST0OVTdj6pW8aztYrDPA8zXGNV+Cy7k4y7sk4V0QLLC8A2nTn7X/63GCIFn7aezwWi6JmZMuG+54qJqpb7sV5vrsUrJ5SV3W5T/9+qek5BnVbzb+WO0a4FHuJidvpxHi3Jl4VlwUVzjmuKVrjHoO7Z8Dxm2WvoK68LZtZsDUeyh1NX5qHp1Br/PX1I52xAEQiyGqM8JQy0S62I3NkmP/EJ1W3Px3yj7KIE+WuY+SyQmuzKo2ad0p8sYWIWfRtwJBerc0b5wQ8hXM0yCWwh6ZAebPMb6TexgDvfUbzPL1HSP7vDoQ9s=
