name: Dev docs

on:
  push:
    branches:
      - github-actions
      - master

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Ubuntu dependencies
      run: sudo apt-get install graphviz pandoc
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.3
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[docs]"
    - name: Build docs
      run: make doc
    - name: Deploy docs
      env:
        GH_TOKEN: ${{ secrets.GitHubToken }}
      run: |
        git config --local user.email "maxhalford25@gmail.com"
        git config --local user.name "MaxHalford"
        mike deploy dev --push --remote https://${GH_TOKEN}@github.com/online-ml/river.git
        echo riverml.xyz > CNAME
        git add CNAME
        git commit -m "Add CNAME"
        git push
