name: dev-docs

on:
  push:
    branches:
      - origin/master

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Ubuntu dependencies
      run: sudo apt-get install graphviz pandoc
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[docs]"
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('setup.py') }}
        restore-keys: |
          pip-
    - name: Build docs
      run: make doc
    - name: Deploy docs
      env:
        GH_TOKEN: ${{ secrets.GitHubToken }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git config pull.rebase false

        git fetch
        git checkout gh-pages
        git pull

        git checkout master
        mike deploy dev --push --remote https://github.com/online-ml/river.git
