name: tests

on: [push, pull_request]

jobs:
  ubuntu:
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]" codecov
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-py{{ matrix.python }}-pip-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-py{{ matrix.python }}-pip-
    - name: Cache datasets
      uses: actions/cache@v2
      with:
        path: ~/river_data
        key: ${{ runner.os }}
    - name: Download datasets
      run: python -c "from river import datasets; datasets.CreditCard().download()"
    - name: pytest
      run: pytest --cov=river -m "not datasets"
    - name: codecov
      run: codecov
