name: unit-tests

on: [pull_request]

jobs:
  ubuntu:
    strategy:
      matrix:
        python: [3.8.1]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python get-pip.py
        python -m pip install --upgrade pip
        pip install -e ".[dev]" codecov
    - name: Cache datasets
      uses: actions/cache@v2
      with:
        path: ~/river_data
        key: ${{ runner.os }}
    - name: Download datasets
      run: python -c "from river import datasets; datasets.CreditCard().download()"
    - name: pytest
      run: pytest --cov=river -m "not datasets"
    - name: codecov
      run: codecov
